### ISSUE TITLE
Category page - ec:addImpression fires for all products regardless of "Products per Page" value

### ISSUE THREAD

**Issue by fweb** [BlueAcornInc/UniversalAnalytics#16]
Magento CE 1.8 with baua 0.5.4

On the category page, ec:addImpression is firing for all products in the category, regardless of the "products per page" value set in Configuration > Catalog > Products per Page [List & Grid]

ec:addProduct has this behavior as well.

Visitor sees: Items 1 to 32 of 421
baua reports: 421 impressions

This artificially inflates the impression metric and probably negative affects performance.

Have I done something wrong in the implementation? Any ideas?

Thank you =]

**Comment by Skrath** [comment]
Hrm, it certainly shouldn't be doing that. I'll have to take a look. What version of Magento are you on?

**Comment by fweb** [comment]
Hi Skrath - 

Sorry was on vacation for a bit. We're on Magento Community 1.8.0.0.

Thanks

**Comment by fweb** [comment]
How can I help fix this issue? Is no one else seeing this?

**Comment by Skrath** [comment]
I haven't heard any other reports from anyone else so far, but I haven't had a chance to really look into this yet. If you have development experience you're more than welcome to look into the bug and submit a pull request (even if it's only a partial solution), and I can take a look at it.

**Comment by fweb** [comment]
Alright so I'm back investigating this now, and I'd like to point out that the MagentoConnect release 0.5.4 is different than the GitHub 0.5.4 release.

Notice that /etc/config.xml are different.

I'm going to have someone help me out on this further, but I just wanted to share that for now.

**Comment by Skrath** [comment]
Well that certainly shouldn't be the case, but it wouldn't be the first time something screwy happened with MagentoConnect...

**Comment by fweb** [comment]
Alright, closing. The issue is caused by AITOC Manufacturers plugin v0.2.6 (now called "Shop by Brands"). Sharing the info below for future reference:

Aitoc_Aitmanufacturers_Block_Manufacturers_Brief::getCategoryItems() is getting called and returning a collection with all the products in the category on line 63

app/code/local/Aitoc/Aitmanufacturers/Block/Manufacturers/Brief.php

Replace lines 63-68 with:
`$productIds = $productCollection->addCategoryFilter(Mage::registry('current_category'))->getAllIds();`

This update will have it use getAllIds() instead of loading the collection and looping over the items to get the ids. This prevents the UA event from firing and should prevent all the products from appearing at the bottom.
