### ISSUE TITLE
best place to report 

### ISSUE THREAD

**Issue by grantkemp** [BlueAcornInc/UniversalAnalytics#19]
Hi guys is the best place to report bugs here, or via the support email on the group.  I sent an email request last week and didn't receive a response yet?

**Comment by Skrath** [comment]
Here is probably the best place, there's sometimes a big delay with the other emails.

**Comment by grantkemp** [comment]
@Skrath  Hey Chris, is this plugin still being actively maintained or is it going to deprecated? - I noticed that there has been several months since it was updated? It would be great to get some clarification as there are quite a few known issues that need to be sorted.

**Comment by Skrath** [comment]
it's still planned to be worked on (by me), but I've got a lot of other projects I'm working on currently. Hopefully I'll be able to get some actual work done on this somewhat soon.
