### ISSUE TITLE
forEach isn't supported in IE8

### ISSUE THREAD

**Issue by ashsmith** [BlueAcornInc/UniversalAnalytics#23]
Use of forEach doesn't work in IE8, and the fix is very simple, just a case of using `.each` instead of `.forEach`. https://github.com/BlueAcornInc/UniversalAnalytics/blob/master/code/Model/Js.php#L31

Happy to submit a PR :)

**Comment by Skrath** [comment]
Hrm, it should be using the Prototype functions for the JS for this (since forEach isn't actually supported by standard JS). I wonder if there might be some additional interaction taking place that's causing an issue here.

**Comment by ashsmith** [comment]
It's not a Prototype js function, forEach is ECMAScript 5: http://caniuse.com/#search=forEach

**Comment by Skrath** [comment]
Yeah, one of our other devs just sent me an email about that. He agrees that changing the usage to `.each` should work just fine.
