### ISSUE TITLE
Javascript error when user goes back a step via checkout without using back button

### ISSUE THREAD

**Issue by grantkemp** [BlueAcornInc/UniversalAnalytics#4]
1. If a customer goes back a step and hasn't selected a shipping method, the module breaks checkout as there is no shipping method to send. 

The expected behaviour is that the GA push will only happen when the user presses the continue button.

**Comment by Skrath** [comment]
Do you have any additional information on the actual error that's occurring? Also, what version of Magento are you seeing this on?

**Comment by grantkemp** [comment]
Yep - its looking for the shipping method value which obviously is null if if you have gone back a step- hence breaking checkout.  

Hi - I am pushing up a PR that I think fixes it but it would be useful if others can check i

**Comment by Skrath** [comment]
I think I've found the issue. Nothing major, just needed to make sure a particular variable existed: dca5189da6d095175914d36335f9ee0f4cfe0d92
